spring:
  application:
    name: jinspace
  config:
    import: optional:configserver:http://localhost:8888
#    profiles:
#        include: oauth
#
#    jpa:
#        database-platform: org.hibernate.dialect.H2Dialect
#        hibernate:
#            ddl-auto: update
#        properties:
#            hibernate:
#                format_sql: true
#                show_sql: true
#        defer-datasource-initialization: true
#
#    h2:
#        console:
#            enabled: true
#
#    datasource:
#        url: jdbc:h2:mem:testdb
#        driverClassName: org.h2.Driver
#        username: sa
#        password:
#
#    session:
#        store-type: jdbc
#
#    security:
#      oauth2:
#        client:
#          registration:
#            naver:
#              client-id: client-id
#              client-secret: client-secret
#              redirect-uri: redirect-uri
#              authorization-grant-type: authorization_code
#              scope:
#                - name
#                - email
#                - profile_image
#              client-name: Naver
#          provider:
#            naver:
#              authorization-uri: authorization-uri
#              token-uri: token-uri
#              user-info-uri: user-info-uri
#              user-name-attribute: response